sources:
  - name: raw
    database: sourcedb
    schema: raw
    tables:
      - name: customers
      - name: accounts
      - name: branch
      - name: transactions
      - name: loan
      - name: cards
      - name: dates
