sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
      - name: accounts
      - name: branch
      - name: transactions
      - name: loan
      - name: credit_card
